POST  http://localhost:3003/api/blogs
content-Type: application/json

  {
    "likes": 40,
    "title": "I kinda like salmon",
    "author": "Timo Toukkavalas",
    "url": "www.whalelife.net",
    "userId": "5dc15b2db78ba13ed09b1a5e"
  }