POST  http://localhost:3003/api/blogs
content-Type: application/json

{
    "title": "How fry butterflies",
    "author": "Larry Greenleaf",
    "url": "www.wonderful-nature.larrysblog.net",
    "likes": 4
}